// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5594aaab-d27f-43f5-9850-5b39998a57a3";

const char SSID[]               = "Halll";    // Network SSID (name)
const char PASS[]               = "xdnu5034";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "e6bwpgV56vRSSEVimfgHYsldL";    // Secret device password

void onBool1Change();
void onAlarm1Change();
void onTime02Change();
void onCityChange();

bool bool_1;
CloudTime alarm_1;
String time02;
int city;


void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(bool_1, READWRITE, ON_CHANGE, onBool1Change);
  ArduinoCloud.addProperty(alarm_1, READWRITE, 2 * SECONDS, onAlarm1Change);
  ArduinoCloud.addProperty(time02, READWRITE, ON_CHANGE, onTime02Change);
  ArduinoCloud.addProperty(city, READWRITE, ON_CHANGE, onCityChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
